jobs:
  - build-test:
      filters:
        branches:
          ignore:
            - main
  - package-test:
      filters:
        branches:
          ignore:
            - main
      requires:
        - build-test
