jobs:
  - build-test:
      filters:
        branches:
          ignore:
            - main
  - package-test:
      requires: build-test
      filters:
        branches:
          ignore:
            - main
