description: Store the build-test cache for pyenv, poetry, and pre-commit
steps:
  - save_cach:
      key: v1-pyenv-{{ arch }}-backend-{{ checksum "poetry.lock" }}
      paths:
        - "~/.pyenv"
  - save_cach:
      key: v1-poetry-{{ arch }}-backend-{{ checksum "poetry.lock" }}
      paths:
        - "~/.cache/pypoetry"
  - save_cach:
      key: v1-precommit-{{ arch }}-backend-{{ checksum "poetry.lock" }}
      paths:
        - "~/.cache/pre-commit"
