description: Store the build-test cache for pyenv, poetry, and pre-commit
steps:
  - save_cache:
      key: v1-pyenv-{{ arch }}-myAES-{{ checksum "poetry.lock" }}
      paths:
        - "~/.pyenv"
  - save_cache:
      key: v1-poetry-{{ arch }}-myAES-{{ checksum "poetry.lock" }}
      paths:
        - "~/.cache/pypoetry"
  - save_cache:
      key: v1-precommit-{{ arch }}-myAES-{{ checksum "poetry.lock" }}
      paths:
        - "~/.cache/pre-commit"
