description: Test that the package can be installed and used
executor: default
steps:
  - checkout
  - circleci-cli/install
  - restore-test-cache
  - poetry-configure
  - run:
      name: Install Dependencies
      command: poetry install
  - run:
      name: Test CLI command
      command: |
        set -eo pipefail

        poetry run myAES test-command --repeat "test phrase"

        if [[ $(!!) != "test phrase" ]]; then

          echo "test command failed to echo given phrase"

          exit 1

        fi
